# system config
LOG_DIR = None
LOG_LEVEL = 'DEBUG'


# Client settings
CLIENT_MQTT_TOPICS = None
CLIENT_KAFKA_TOPICS = None
CLIENT_AMQP_QUEUE = None
CLIENT_KAFKA_GROUP_ID = None
CLIENT_URI = None
CLIENT_USERNAME = None
CLIENT_PASSWORD = None
CLIENT_MOCK_INTERVAL = 60
CLIENT_FILTER_ENABLED = False
CLIENT_FILTER_IS_INCLUDING = True

# LoRa server settings
LORA_DRIVER = None

# Producer settings
PRODUCER_DRIVER = None
PRODUCER_TARGET = None
PRODUCER_HOSTS = None
PRODUCER_DATABASE = None
PRODUCER_USERNAME = None
PRODUCER_PASSWORD = None
PRODUCER_REGION = None
